### ISSUE TITLE
Colorscheme does not identify itself properly.

### ISSUE THREAD

**Issue by UrsaDK** [albertorestifo/github.vim#3]
Once loaded, the colorscheme does not expose `g:colors_name` variable. As a result, `:colorscheme` identifies this plugin as `default` rather then `github`.

**Comment by UrsaDK** [comment]
This happens because `hl clear` removes `g:colors_name`.
Setting `g:colors_name` after `hl clear` resolves the issue.

**Comment by albertorestifo** [comment]
Currently the theme is generated with [estilo](https://github.com/jacoborus/estilo). I plan to move away from it anyway to maintain the theme as a vanilla colorscheme.

Until then this bug will remain unfixed.

Could this also explain why the airline theme is not being selected automatically?

**Comment by UrsaDK** [comment]
This bug will break anything that relies on identifying the theme, either via the `:colorscheme` command or via the `g:colors_name` variable.  The thing is, that's the two most common ways of identifying an active colorscheme, so anything that targets this theme via it's name would be affected.

As for the airline theme, I don't use airline my self, so not 100% sure as to how it works or how airline theme is suppose to be initialised. Do you know what function is called to load the theme?

Sorry if I'm covering complete basics here, but the thing about the autoload directory is that the code in it is not automatically loaded. [Learn Vimscript the Hard Way](http://learnvimscriptthehardway.stevelosh.com/chapters/53.html) explains it really well, but the key point is that for the code to be autoloaded it needs to be called from somewhere first.

**Comment by albertorestifo** [comment]
@UmkaDK Thanks for the quick lesson!

I digged a bit in the code an sure enough, [`vim-airline` relies on that variable to match the colorscheme][1].

I hope to have time for the update to a vanilla theme this week.

[1]: https://github.com/vim-airline/vim-airline/blob/master/autoload/airline.vim#L76

**Comment by UrsaDK** [comment]
No worries, glad I could have helped!

> I hope to have time for the update to a vanilla theme this week.

In that case, I've noticed that there are a couple of highlight groups missing... Raised #4 to address this. 😄

**Comment by albertorestifo** [comment]
Sorry for the delay. I'll start working on the improvments and also, update the colors as GitHub changed colorscheme

**Comment by albertorestifo** [comment]
Solved in latest update
