### ISSUE TITLE
Missing highlights for SpecialKey & SignColumn

### ISSUE THREAD

**Issue by UrsaDK** [albertorestifo/github.vim#4]
Highlights for the following groups are missing:

SignColumn - used by https://github.com/kshenoy/vim-signature to display marks.
SpecialKey - used to show unprintable characters in the text, 'listchars', eg: trailing white space.

Both can be easily fixed by adding:
```
hi link SpecialKey NonText
hi SignColumn guibg=NONE ctermbg=NONE gui=NONE cterm=NONE
```

**Comment by UrsaDK** [comment]
An even better solution might be to define SignColumn as:
```
hi SignColumn guifg=#0086b3 ctermfg=31 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE
```

On one hand, this would provide a sort of colour guide for anyone wishing to use marks, allowing them to link to a fully styled highlight group, eg: ` hi link SignatureMarkText SignColumn`. On the other hand, it would ensure that marks are distinctly different to git-diff signs placed by, for example, [vim-gitgutter](https://github.com/airblade/vim-gitgutter).

**Comment by albertorestifo** [comment]
Resolved in latest update
