### ISSUE TITLE
Search and IncSearch use the same colour.

### ISSUE THREAD

**Issue by UrsaDK** [albertorestifo/github.vim#6]
At the moment Search and IncSearch highlight groups use the same colour. This can get a little confusing when you have `set hlsearch incsearch` and you are searching for fragments of a CamelCase word.

**How to recreate**

1. Start a new buffer and run the following commands:
```viml
:colorscheme github
:set hlsearch incsearch
:normal ggiThisIsMyTest
```
2. Search for `Test` and hit Enter
3. Search for `MyT` but do not hit Enter

Now my IncSearch highlight is merged with the previous Search highlight and it appears that highlighted string is "MyTest"?

**My solution**

... is to use a slightly different colour for IncSearch, eg:

```viml
hi IncSearch guibg=#ffb4e3 ctermbg=217
```
This doesn't match any of the "official" github colours, but `incsearch` is a feature not available on github, so I think it should be ok to use a different colour. 

I did tried to stay with in the gamma pallet of the theme. :)

**Comment by albertorestifo** [comment]
Resolved in latest update
